### ISSUE TITLE
Create TF->Distance tool for end-effector camera for visual servoing

### ISSUE THREAD

**Issue by jpanikulam** [ufieeehw/IEEE2015#20]
Given a position in pixel space, determine the position of that pixel in world-space, if you know the height of the object containing that pixel.

Uses:
- Figure out the necessary motion of the arm for visual servoing.
- Aid the object recognition work by enabling them to know scale and (hopefully) orientation in advance. Scale is more important, though.
- Augment main-camera pose estimation

How it should look:
Using the TF node created in #19, add [a service ](http://wiki.ros.org/ROS/Tutorials/WritingServiceClient%28python%29) proxy that you can call from another ROS node, give it two pixel positions, and get a world-distance between them. And another service that given a single pixel, will return the world position of that pixel.

**Comment by LucasBA** [comment]
Its done.
